bubble_sort_no_escape_clause: bubble_sort_no_escape_clause.cpp file_handling.h
	g++ -o bubble_sort_no_escape_clause bubble_sort_no_escape_clause.cpp -fopenmp

bubble_sort_escape_clause: bubble_sort_escape_clause.cpp
	g++ -o bubble_sort_escape_clause bubble_sort_escape_clause.cpp -fopenmp

clean:
	rm bubble_sort_no_escape_clause bubble_sort_escape_clause